
/*
 * Business Process Definition: Term Go Live Process (term_go_live_wf)
 *
 * Auto-generated by ACS Workflow Export, version 4.3
 *
 * Context: default
 */


/*
 * Cases table
 */
create table term_go_live_process_cases (
  case_id               integer primary key
                        references wf_cases on delete cascade
);

/* 
 * Declare the object type
 */

declare
    v_workflow_key varchar2(40);
begin
    v_workflow_key := workflow.create_workflow(
        workflow_key => 'term_go_live_wf', 
        pretty_name => 'Term Go Live Process', 
        pretty_plural => 'Term Go Live Processes', 
        description => 'User submits new term and its definition (and maybe illustration) and it goes live immediately.', 
        table_name => 'term_go_live_process_cases'
    );
end;
/
show errors

        


/*****
 * Places
 *****/

/*****
 * Roles
 *****/



/*****
 * Transitions
 *****/



/*****
 * Arcs
 *****/



/*****
 * Attributes
 *****/


/*****
 * Transition-role-assignment-map
 *****/



/*
 * Context/Transition info
 * (for context = default)
 */



/*
 * Context/Role info
 * (for context = default)
 */



/*
 * Context Task Panels
 * (for context = default)
 */


commit;

