
/*
 * Business Process Definition: Term Go Live Process (term_go_live_wf)
 *
 * Auto-generated by ACS Workflow Export, version 4.3
 *
 * Context: default
 */


/*
 * Cases table
 */
create table term_go_live_process_cases (
  case_id               integer primary key
                        references wf_cases on delete cascade
);

/* 
 * Declare the object type
 */


create function inline_0 () returns integer as '
begin
    PERFORM workflow__create_workflow (
        ''term_go_live_wf'', 
        ''Term Go Live Process'', 
        ''Term Go Live Processes'', 
        ''User submits new term and its definition (and maybe illustration) and it goes live immediately.'', 
        ''term_go_live_process_cases'',
        ''case_id''
    );

    return null;

end;' language 'plpgsql';

select inline_0 ();
drop function inline_0 ();

        


/*****
 * Places
 *****/

/*****
 * Roles
 *****/



/*****
 * Transitions
 *****/



/*****
 * Arcs
 *****/



/*****
 * Attributes
 *****/


/*****
 * Transition-role-assignment-map
 *****/



/*
 * Context/Transition info
 * (for context = default)
 */



/*
 * Context/Role info
 * (for context = default)
 */



/*
 * Context Task Panels
 * (for context = default)
 */


commit;
